import type { ProviderInfo } from "../settingsTypes"

// Local provider is handled separately (no API key, managed via Local AI settings)
export const LOCAL_PROVIDER: ProviderInfo = {
  id: "local",
  name: "Local AI",
  type: "local",
  freeTier: true,
  freeNote: "Runs on your machine — no API key needed",
  description: "Run models locally via llama.cpp (GGUF)",
  models: [], // Dynamic — populated from installed models
}

export const PROVIDER_CATALOG: ProviderInfo[] = [
  {
    id: "anthropic",
    name: "Anthropic",
    type: "anthropic",
    envVar: "ANTHROPIC_API_KEY",
    signupUrl: "https://console.anthropic.com/",
    description: "$5 free credits on signup",
    models: [
      {
        id: "claude-opus-4-20250514",
        name: "Claude Opus 4",
        contextWindow: 200_000,
        maxOutput: 64_000,
        reasoning: true,
        toolCalling: true,
        vision: true,
        costPer1kInput: 0.005,
        costPer1kOutput: 0.025,
      },
      {
        id: "claude-sonnet-4-20250514",
        name: "Claude Sonnet 4",
        contextWindow: 200_000,
        maxOutput: 64_000,
        reasoning: true,
        toolCalling: true,
        vision: true,
        costPer1kInput: 0.003,
        costPer1kOutput: 0.015,
      },
      {
        id: "claude-haiku-4-5-20251001",
        name: "Claude Haiku 4.5",
        contextWindow: 200_000,
        maxOutput: 64_000,
        reasoning: false,
        toolCalling: true,
        vision: true,
        costPer1kInput: 0.0008,
        costPer1kOutput: 0.004,
      },
    ],
  },
  {
    id: "openai",
    name: "OpenAI",
    type: "openai",
    envVar: "OPENAI_API_KEY",
    signupUrl: "https://platform.openai.com/api-keys",
    description: "Pay-as-you-go, no free tier",
    models: [
      {
        id: "gpt-4o",
        name: "GPT-4o",
        contextWindow: 128_000,
        maxOutput: 64_000,
        reasoning: false,
        toolCalling: true,
        vision: true,
        costPer1kInput: 0.0025,
        costPer1kOutput: 0.01,
      },
      {
        id: "gpt-4o-mini",
        name: "GPT-4o Mini",
        contextWindow: 128_000,
        maxOutput: 64_000,
        reasoning: false,
        toolCalling: true,
        vision: true,
        costPer1kInput: 0.00015,
        costPer1kOutput: 0.0006,
      },
      {
        id: "o3-mini",
        name: "o3-mini",
        contextWindow: 128_000,
        maxOutput: 64_000,
        reasoning: true,
        toolCalling: true,
        vision: false,
        costPer1kInput: 0.0011,
        costPer1kOutput: 0.0044,
      },
    ],
  },
  {
    id: "google",
    name: "Google",
    type: "google",
    envVar: "GOOGLE_GENERATIVE_AI_API_KEY",
    freeTier: true,
    freeNote: "Free tier available with rate limits",
    signupUrl: "https://aistudio.google.com/apikey",
    description: "Free API key, generous rate limits",
    models: [
      {
        id: "gemini-2.5-pro",
        name: "Gemini 2.5 Pro",
        contextWindow: 1_000_000,
        maxOutput: 65_000,
        reasoning: true,
        toolCalling: true,
        vision: true,
        costPer1kInput: 0.00125,
        costPer1kOutput: 0.01,
      },
      {
        id: "gemini-2.5-flash",
        name: "Gemini 2.5 Flash",
        contextWindow: 1_000_000,
        maxOutput: 65_000,
        reasoning: false,
        toolCalling: true,
        vision: true,
        costPer1kInput: 0.000075,
        costPer1kOutput: 0.0003,
      },
    ],
  },
  {
    id: "mistral",
    name: "Mistral",
    type: "mistral",
    envVar: "MISTRAL_API_KEY",
    signupUrl: "https://console.mistral.ai/api-keys",
    description: "Pay-as-you-go, Codestral free for coding",
    models: [
      {
        id: "mistral-large-latest",
        name: "Mistral Large",
        contextWindow: 128_000,
        maxOutput: 32_000,
        reasoning: false,
        toolCalling: true,
        vision: false,
        costPer1kInput: 0.002,
        costPer1kOutput: 0.006,
      },
      {
        id: "codestral-latest",
        name: "Codestral",
        contextWindow: 256_000,
        maxOutput: 32_000,
        reasoning: false,
        toolCalling: true,
        vision: false,
        costPer1kInput: 0.0003,
        costPer1kOutput: 0.0009,
      },
    ],
  },
  {
    id: "groq",
    name: "Groq",
    type: "groq",
    envVar: "GROQ_API_KEY",
    freeTier: true,
    freeNote: "Free tier with generous rate limits",
    signupUrl: "https://console.groq.com/keys",
    description: "Free tier, ultra-fast inference",
    models: [
      {
        id: "llama-3.3-70b-versatile",
        name: "Llama 3.3 70B",
        contextWindow: 128_000,
        maxOutput: 32_000,
        reasoning: false,
        toolCalling: true,
        vision: false,
      },
      {
        id: "qwen-qwq-32b",
        name: "QwQ 32B (Reasoning)",
        contextWindow: 128_000,
        maxOutput: 16_000,
        reasoning: true,
        toolCalling: true,
        vision: false,
      },
    ],
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    type: "openrouter",
    envVar: "OPENROUTER_API_KEY",
    freeTier: true,
    freeNote: "Some free models available",
    signupUrl: "https://openrouter.ai/keys",
    description: "Multi-provider gateway, some free models",
    models: [
      {
        id: "anthropic/claude-sonnet-4",
        name: "Claude Sonnet 4 (via OpenRouter)",
        contextWindow: 200_000,
        maxOutput: 64_000,
        reasoning: true,
        toolCalling: true,
        vision: true,
      },
      {
        id: "openai/gpt-4o",
        name: "GPT-4o (via OpenRouter)",
        contextWindow: 128_000,
        maxOutput: 64_000,
        reasoning: false,
        toolCalling: true,
        vision: true,
      },
      {
        id: "google/gemini-2.5-pro",
        name: "Gemini 2.5 Pro (via OpenRouter)",
        contextWindow: 1_000_000,
        maxOutput: 65_000,
        reasoning: true,
        toolCalling: true,
        vision: true,
      },
      {
        id: "deepseek/deepseek-chat-v3",
        name: "DeepSeek Chat v3 (via OpenRouter)",
        contextWindow: 64_000,
        maxOutput: 8_000,
        reasoning: false,
        toolCalling: true,
        vision: false,
      },
    ],
  },
  {
    id: "xai",
    name: "xAI",
    type: "xai",
    envVar: "XAI_API_KEY",
    freeTier: true,
    freeNote: "$25 free credits monthly",
    signupUrl: "https://console.x.ai/",
    description: "$25/mo free credits for Grok",
    models: [
      {
        id: "grok-3",
        name: "Grok 3",
        contextWindow: 128_000,
        maxOutput: 32_000,
        reasoning: true,
        toolCalling: true,
        vision: false,
      },
      {
        id: "grok-3-mini",
        name: "Grok 3 Mini",
        contextWindow: 128_000,
        maxOutput: 16_000,
        reasoning: false,
        toolCalling: true,
        vision: false,
      },
    ],
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    type: "deepseek",
    envVar: "DEEPSEEK_API_KEY",
    signupUrl: "https://platform.deepseek.com/api_keys",
    description: "Very cheap, great reasoning models",
    models: [
      {
        id: "deepseek-chat",
        name: "DeepSeek Chat",
        contextWindow: 64_000,
        maxOutput: 8_000,
        reasoning: false,
        toolCalling: true,
        vision: false,
        costPer1kInput: 0.00027,
        costPer1kOutput: 0.0011,
      },
      {
        id: "deepseek-reasoner",
        name: "DeepSeek Reasoner",
        contextWindow: 64_000,
        maxOutput: 8_000,
        reasoning: true,
        toolCalling: true,
        vision: false,
        costPer1kInput: 0.00054,
        costPer1kOutput: 0.00219,
      },
    ],
  },
  {
    id: "togetherai",
    name: "Together AI",
    type: "togetherai",
    envVar: "TOGETHER_AI_API_KEY",
    freeTier: true,
    freeNote: "Some free models available",
    signupUrl: "https://api.together.ai/settings/api-keys",
    description: "$5 free credits on signup",
    models: [
      {
        id: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
        name: "Llama 3.3 70B Turbo",
        contextWindow: 128_000,
        maxOutput: 4_000,
        reasoning: false,
        toolCalling: true,
        vision: false,
      },
      {
        id: "deepseek-ai/DeepSeek-R1",
        name: "DeepSeek R1",
        contextWindow: 64_000,
        maxOutput: 8_000,
        reasoning: true,
        toolCalling: true,
        vision: false,
      },
    ],
  },
  {
    id: "perplexity",
    name: "Perplexity",
    type: "perplexity",
    envVar: "PERPLEXITY_API_KEY",
    signupUrl: "https://www.perplexity.ai/settings/api",
    description: "Search-augmented AI, pay-as-you-go",
    models: [
      {
        id: "sonar-pro",
        name: "Sonar Pro",
        contextWindow: 128_000,
        maxOutput: 8_000,
        reasoning: false,
        toolCalling: true,
        vision: false,
        costPer1kInput: 0.003,
        costPer1kOutput: 0.015,
      },
      {
        id: "sonar-reasoning-pro",
        name: "Sonar Reasoning Pro",
        contextWindow: 128_000,
        maxOutput: 8_000,
        reasoning: true,
        toolCalling: true,
        vision: false,
        costPer1kInput: 0.002,
        costPer1kOutput: 0.008,
      },
    ],
  },
  {
    id: "fireworks",
    name: "Fireworks AI",
    type: "fireworks",
    envVar: "FIREWORKS_API_KEY",
    freeTier: true,
    freeNote: "Free tier with rate limits",
    signupUrl: "https://fireworks.ai/api-keys",
    description: "Free tier, fast open-source models (limited tool support)",
    models: [
      {
        id: "accounts/fireworks/models/llama-v3p3-70b-instruct",
        name: "Llama 3.3 70B Instruct",
        contextWindow: 128_000,
        maxOutput: 8_000,
        reasoning: false,
        toolCalling: false, // Fireworks returns tool calls as raw text, not structured
        vision: false,
      },
    ],
  },
  {
    id: "cerebras",
    name: "Cerebras",
    type: "cerebras",
    envVar: "CEREBRAS_API_KEY",
    freeTier: true,
    freeNote: "Free tier with fast inference",
    signupUrl: "https://cloud.cerebras.ai/",
    description: "Free tier, fastest inference available",
    models: [
      {
        id: "llama-3.3-70b",
        name: "Llama 3.3 70B",
        contextWindow: 128_000,
        maxOutput: 8_000,
        reasoning: false,
        toolCalling: true,
        vision: false,
      },
      {
        id: "llama-3.1-8b",
        name: "Llama 3.1 8B",
        contextWindow: 128_000,
        maxOutput: 8_000,
        reasoning: false,
        toolCalling: true,
        vision: false,
      },
    ],
  },
  {
    id: "cohere",
    name: "Cohere",
    type: "cohere",
    envVar: "COHERE_API_KEY",
    freeTier: true,
    freeNote: "Free trial API key",
    signupUrl: "https://dashboard.cohere.com/api-keys",
    description: "Free trial key, rate-limited",
    models: [
      {
        id: "command-a-03-2025",
        name: "Command A",
        contextWindow: 256_000,
        maxOutput: 8_000,
        reasoning: false,
        toolCalling: true,
        vision: false,
        costPer1kInput: 0.0025,
        costPer1kOutput: 0.01,
      },
    ],
  },
]
