import type { ThemeDefinition } from "../settingsTypes"

export const THEMES: ThemeDefinition[] = [
  {
    id: "exegol-dark",
    name: "Exegol Dark",
    colors: {
      "surface-0": "#000000",
      "surface-1": "#0d0d0d",
      "surface-2": "#1e1e1e",
      "surface-3": "#262626",
      "text-strong": "#f9fafb",
      "text-base": "#d1d5db",
      "text-weak": "#9ca3b0",
      "text-weaker": "#747c8a",
      "border-base": "#262626",
      "border-weak": "#1e1e1e",
      accent: "#8957e5",
      "accent-hover": "#7c3aed",
      "status-success": "#42c170",
      "status-error": "#df4e4e",
      "status-warning": "#facc15",
    },
  },
  {
    id: "exegol-light",
    name: "Exegol Light",
    colors: {
      "surface-0": "#ffffff",
      "surface-1": "#fafafa",
      "surface-2": "#efefef",
      "surface-3": "#e4e4e4",
      "text-strong": "#0f0f0f",
      "text-base": "#5e6065",
      "text-weak": "#7e7f81",
      "text-weaker": "#9ca3b0",
      "border-base": "#e4e4e4",
      "border-weak": "#efefef",
      accent: "#8957e5",
      "accent-hover": "#7c3aed",
      "status-success": "#42c170",
      "status-error": "#df4e4e",
      "status-warning": "#facc15",
    },
  },
  {
    id: "midnight",
    name: "Midnight",
    colors: {
      "surface-0": "#0a0e1a",
      "surface-1": "#0f1425",
      "surface-2": "#161c32",
      "surface-3": "#1e2540",
      "text-strong": "#e8ecf4",
      "text-base": "#b8c4da",
      "text-weak": "#8494b4",
      "text-weaker": "#5a6a8a",
      "border-base": "#1c2440",
      "border-weak": "#141c34",
      accent: "#7c3aed",
      "accent-hover": "#6d28d9",
      "status-success": "#42c170",
      "status-error": "#df4e4e",
      "status-warning": "#facc15",
    },
  },
  {
    id: "dracula",
    name: "Dracula",
    colors: {
      "surface-0": "#282a36",
      "surface-1": "#2d303e",
      "surface-2": "#343746",
      "surface-3": "#3c3f50",
      "text-strong": "#f8f8f2",
      "text-base": "#d4d4ce",
      "text-weak": "#a4a4a0",
      "text-weaker": "#6272a4",
      "border-base": "#44475a",
      "border-weak": "#383a4c",
      accent: "#bd93f9",
      "accent-hover": "#a87cf8",
      "status-success": "#50fa7b",
      "status-error": "#ff5555",
      "status-warning": "#f1fa8c",
    },
  },
  {
    id: "nord",
    name: "Nord",
    colors: {
      "surface-0": "#2e3440",
      "surface-1": "#333a47",
      "surface-2": "#3b4252",
      "surface-3": "#434c5e",
      "text-strong": "#eceff4",
      "text-base": "#d8dee9",
      "text-weak": "#a3b1c4",
      "text-weaker": "#7b8da0",
      "border-base": "#434c5e",
      "border-weak": "#3b4252",
      accent: "#88c0d0",
      "accent-hover": "#7ab3c3",
      "status-success": "#a3be8c",
      "status-error": "#bf616a",
      "status-warning": "#ebcb8b",
    },
  },
  {
    id: "catppuccin",
    name: "Catppuccin Mocha",
    colors: {
      "surface-0": "#1e1e2e",
      "surface-1": "#232334",
      "surface-2": "#2a2a3c",
      "surface-3": "#313244",
      "text-strong": "#cdd6f4",
      "text-base": "#bac2de",
      "text-weak": "#a6adc8",
      "text-weaker": "#6c7086",
      "border-base": "#313244",
      "border-weak": "#282838",
      accent: "#cba6f7",
      "accent-hover": "#b48def",
      "status-success": "#a6e3a1",
      "status-error": "#f38ba8",
      "status-warning": "#f9e2af",
    },
  },
  {
    id: "light",
    name: "Light",
    colors: {
      "surface-0": "#ffffff",
      "surface-1": "#f8fafc",
      "surface-2": "#f1f5f9",
      "surface-3": "#e2e8f0",
      "text-strong": "#0f172a",
      "text-base": "#1e293b",
      "text-weak": "#475569",
      "text-weaker": "#94a3b8",
      "border-base": "#e2e8f0",
      "border-weak": "#f1f5f9",
      accent: "#8957e5",
      "accent-hover": "#7c3aed",
      "status-success": "#42c170",
      "status-error": "#df4e4e",
      "status-warning": "#facc15",
    },
  },
]
